# Generated by Django 5.0.1 on 2024-01-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('exercise_image', models.FileField(default=None, max_length=250, null=True, upload_to='images/')),
            ],
        ),
    ]
