# Generated by Django 5.0.1 on 2024-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('desc', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise_image',
            new_name='image_file',
        ),
        migrations.AddField(
            model_name='exercise',
            name='desc',
            field=models.TextField(default=None, null=True),
        ),
    ]
