# Generated by Django 5.0.1 on 2024-01-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_contact_rename_exercise_image_exercise_image_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excercisepost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeexercise', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(default=None, null=True)),
                ('video_file', models.FileField(default=None, max_length=250, null=True, upload_to='videos/')),
                ('thumbnail', models.FileField(default=None, max_length=250, null=True, upload_to='images/')),
            ],
        ),
    ]
