# Generated by Django 5.0.1 on 2024-01-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_excercisepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excercisepost',
            name='video_file',
        ),
        migrations.AddField(
            model_name='excercisepost',
            name='videolink',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
