# Generated by Django 5.0.1 on 2024-02-19 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_remove_excercisepost_video_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(default=None, null=True)),
                ('image_file', models.FileField(default=None, max_length=250, null=True, upload_to='images/')),
            ],
        ),
    ]
