# Generated by Django 5.0.1 on 2024-02-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_dietcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(default=None, null=True)),
                ('diet_image', models.FileField(default=None, max_length=250, null=True, upload_to='images/')),
            ],
        ),
    ]
