# Generated by Django 5.0.1 on 2024-02-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_dietposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietposts',
            name='dietContent',
            field=models.TextField(default=None, null=True),
        ),
    ]
