# Generated by Django 5.0.1 on 2024-02-20 08:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_dietposts_dietcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietposts',
            name='dietContent',
            field=ckeditor.fields.RichTextField(default=None),
            preserve_default=False,
        ),
    ]
