# Generated by Django 5.0.1 on 2024-02-20 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0008_alter_dietposts_dietcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietposts',
            name='dietContent',
        ),
    ]
