# Generated by Django 5.0.1 on 2024-02-21 02:44

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0009_remove_dietposts_dietcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietposts',
            name='dietContent',
            field=django_ckeditor_5.fields.CKEditor5Field(default=None, null=True),
        ),
    ]
