# Generated by Django 5.0.2 on 2024-02-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_dietposts_dietcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
