# Generated by Django 5.0.2 on 2024-02-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_remove_contact_phone_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.TextField(max_length=100),
        ),
    ]
